job: extension
config:
  name: my_first_flux_lora_v1
  process:
  - type: sd_trainer
    training_folder: ./output_with_90_percent_images
    device: cuda:0
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      save_every: 250
      max_step_saves_to_keep: 500000
    datasets:
    - folder_path: ./training_dataset_90
      caption_ext: txt
      caption_dropout_rate: 0.02
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 256
      - 256
    train:
      batch_size: 4
      steps: 100001
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: true
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 5.0e-05
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: black-forest-labs/FLUX.1-schnell
      assistant_lora_path: ostris/FLUX.1-schnell-training-adapter
      is_flux: true
      quantize: true
      resume_checkpoint: ./output_with_90_percent_images/my_first_flux_lora_v1/my_first_flux_lora_v1_000070000.safetensors
    sample:
      sampler: flowmatch
      sample_every: 250
      width: 256
      height: 256
      prompts:
      - 1 balcony 50 sqft ratio 13:3 green, master room 200 sqft ratio 7:11 yellow,
        bathroom 100 sqft ratio 1:1 blue, common room 150 sqft ratio 15:16 orange,
        2 balcony 23 sqft ratio 13:9 green, living room 800 sqft ratio 11:9 light
        yellow.
      - master room 150 sqft ratio 13:16 yellow, balcony 50 sqft ratio 16:5 green,
        kitchen 50 sqft ratio 5:3 coral red, common room 150 sqft ratio 5:7 orange,
        living room 650 sqft ratio 7:12 light yellow, bathroom 50 sqft ratio 16:15
        blue.
      - balcony 50 sqft ratio 16:3 green, kitchen 100 sqft ratio 13:8 coral red, common
        room 200 sqft ratio 7:5 orange, bathroom 50 sqft ratio 12:5 blue, master room
        200 sqft ratio 16:13 yellow, living room 450 sqft ratio 15:16 light yellow.
      - bathroom 50 sqft ratio 8:15 blue, common room 200 sqft ratio 11:16 orange,
        master room 200 sqft ratio 11:16 yellow, living room 250 sqft ratio 4:3 light
        yellow, kitchen 50 sqft ratio 5:8 coral red.
      - 1 common room 100 sqft ratio 16:15 orange, 2 common room 100 sqft ratio 1:1
        orange, master room 200 sqft ratio 15:16 yellow, 3 common room 200 sqft ratio
        15:14 orange, bathroom 50 sqft ratio 5:6 blue, living room 550 sqft ratio
        8:15 light yellow, kitchen 50 sqft ratio 13:7 coral red, balcony 16 sqft ratio
        6:11 green.
      - kitchen 100 sqft ratio 2:1 coral red, bathroom 50 sqft ratio 10:7 blue, common
        room 150 sqft ratio 1:1 orange, master room 200 sqft ratio 2:3 yellow, balcony
        50 sqft ratio 11:4 green, living room 500 sqft ratio 1:3 light yellow.
      - 1 common room 100 sqft ratio 14:11 orange, living room 1100 sqft ratio 14:9
        light yellow, balcony 100 sqft ratio 14:5 green, master room 200 sqft ratio
        15:16 yellow, 2 common room 200 sqft ratio 6:7 orange, bathroom 50 sqft ratio
        8:11 blue, kitchen 50 sqft ratio 6:7 coral red.
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 1
      sample_steps: 4
    callbacks:
    - type: early_stopping
      patience: 5
      verbose: true
meta:
  name: my_first_flux_lora_v1
  version: '1.0'
